name: Build runtime image in ACR and deploy to App Service

on:
 workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'biomni-app-host'
  IMAGE_NAME: 'biomni-app'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Free up disk space on the runner by removing unneeded software.
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # This removes Android and Haskell toolchains
          tool-cache: false
          android: true
          haskell: true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push runtime image to ACR
        run: |
          docker build . -f Dockerfile.runtime -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'
